---

- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    
  - name: Get version of RPM
    shell:  yum list installed openssl | grep openssl | awk '{print $2}' | cut -d'-' -f1
    register: version
    changed_when: False
    args:
      warn: no
    debug: msg="{{ version }}"
