---

- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    
  - name: get the rpm or apt package facts
    package_facts:
      manager: "auto"

  - name: show openssl version
    debug: var=ansible_facts.packages.openssl[0].version
