- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    
  - name: use command to pull version
    command: '/usr/bin/rpm -qa custom-rpm --queryformat %{VERSION}'
    register: version
    ignore_warnings: True
    changed_when: False
